### PR TITLE
fix: address compilation warnings

### PR DESCRIPTION
**Pull request by m-clare**
Noticed a few warnings on compilation for deprecated methods. Replaced with new methods.

### CODE REVIEW

**Comment by dancergraham** [comment]
Awesome you fixed it ! I spent a bunch of time failing to find the right combination of methods and type annotations for this !

**Comment by m-clare** [comment]
@dancergraham did you mean to close this? Or just wanted to put it on hold for later?

**Comment by dancergraham** [comment]
Ooh I wanted to close and merge it - did I press the wrong button in the morning fog?

**Comment by dancergraham** [comment]
Ok I think I got the right one this time 🤦‍♂️

**Pull request merged**
